home:
   path: /
   controller: App\Controller\HomeController::Home

annonces:
   path: /annonces
   controller: App\Controller\AnnonceController::index

add:
   path: /annonce/add
   controller: App\Controller\AnnonceController::createAnnonce

annonce:
   path: /annonce/{slug}
   controller: App\Controller\AnnonceController::showOneAnnonce

edit:
   path: /annonce/{slug}/edit
   controller: App\Controller\AnnonceController::editAnnonce

delete:
   path: /annonce/{slug}/delete
   controller: App\Controller\AnnonceController:deleteAnnonce

login:
   path: /login
   controller: App\Controller\AccountController::login

logout:
   path: /logout

register:
   path: /register
   controller: App\Controller\AccountController::register

profil:
   path: /account/profil
   controller: App\Controller\AccountController::editProfil

change-password:
   path: /account/change-password
   controller: App\Controller\AccountController::changePassword

user:
   path: /user/{slug}
   controller: App\Controller\UserController::index

myaccount:
   path: /account
   controller: App\Controller\AccountController::myAccount

reserver:
   path: /annonce/{slug}/reserver
   controller: App\Controller\ReservationController:reserver

show-reservation:
   path: /reservation/{id}
   controller: App\Controller\ReservationController:show

reservations:
   path: /account/reservations
   controller: App\Controller\AccountController:reservations

admin_login:
   path: /admin/login
   controller: App\Controller\AdminAccountController:login

admin_logout:
   path: /admin/logout
   controller: App\Controller\AdminAccountController:logout

admin_annonces_index:
   path: /admin/annonces
   controller: App\Controller\AdminAnnonceController:index

edit_admin_annonce:
   path: /admin/annonces/{id}/edit
   controller: App\Controller\AdminAccountController::editAnnonce

delete_admin_annonce:
   path: /admin/annonces/{id}/delete
   controller: App\Controller\AdminAccountController::deleteAnnonce

admin_comments_index:
   path: /admin/comments
   controller: App\Controller\AdminCommentController:index

edit_admin_comment:
   path: /admin/comments/{id}/edit
   controller: App\Controller\AdminCommentController::editComment

delete_admin_comment:
   path: /admin/comments/{id}/delete
   controller: App\Controller\AdminCommentController::deleteComment


