home:
   path: /
   controller: App\Controller\HomeController::Home

annonces:
   path: /annonces
   controller: App\Controller\AnnonceController::index

add:
   path: /annonce/add
   controller: App\Controller\AnnonceController::createAnnonce

annonce:
   path: /annonce/{slug}
   controller: App\Controller\AnnonceController::showOneAnnonce

edit:
   path: /annonce/{slug}/edit
   controller: App\Controller\AnnonceController::editAnnonce

login:
   path: /login
   controller: App\Controller\AccountController::login

logout:
   path: /logout

register:
   path: /register
   controller: App\Controller\AccountController::register
